version: 0.2
phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --no-include-email --region us-west-2)
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...          
      - docker build -t webservergt:latest .
      - docker tag webservergt:latest 709973393692.dkr.ecr.us-west-2.amazonaws.com/webservergt:latest
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push 709973393692.dkr.ecr.us-west-2.amazonaws.com/webservergt:latest
