version: 0.2
phases:
  install:
    commands:
      - docker login -u $dockerhub_username -p $dockerhub_password
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region us-west-2 | docker login --username AWS --password-stdin 709973393692.dkr.ecr.us-west-2.amazonaws.com/webservergt
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...          
      - docker build -t webservergt:3.0 .
      - docker tag webservergt:3.0 709973393692.dkr.ecr.us-west-2.amazonaws.com/webservergt:3.0
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push 709973393692.dkr.ecr.us-west-2.amazonaws.com/webservergt:3.0
